baseURL = 'https://kumekay.com/'
languageCode = 'en-us'
title = 'kumekay'

[permalinks.page]
posts = '/:slug/'

# Taxonomies
[taxonomies]
tag = 'tags'

[outputs]
home = ['html', 'rss']
section = ['html', 'json']
taxonomy = ['html']
term = ['html']

[outputFormats.JSON]
baseName = 'index'
mediaType = 'application/json'

# Markdown rendering
[markup.goldmark.renderer]
unsafe = true # Allow raw HTML in markdown (for headerHtml)

# Site params
[params]
author = 'Sergei Silnov'
