daemon off;
error_log /dev/stderr;

events {}

http {
    include /etc/nginx/mime.types;
    access_log /dev/stdout;
    
    server {
        listen 8080;
        root /app/public;
        try_files $uri $uri/ =404;
    }
}
